# syntax=docker/dockerfile:1

# --- Build stage ---
FROM golang:1.24-alpine AS builder

RUN apk add --no-cache upx ca-certificates

WORKDIR /app

COPY pkg ./pkg
COPY services/{{.Name}} ./services/{{.Name}}

WORKDIR /app/services/{{.Name}}

ENV GOMAXPROCS=$(nproc)

RUN --mount=type=cache,target=/go/pkg/mod go mod download -v
RUN CGO_ENABLED=0 GOOS=linux go build -o {{.Name}}-service -ldflags="-s -w" ./src/cmd
RUN upx --best --lzma {{.Name}}-service || true

# --- Run stage ---
FROM scratch

WORKDIR /app

COPY --from=builder /app/services/{{.Name}}/{{.Name}}-service ./{{.Name}}-service
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY .env .env

EXPOSE {{.Port}}
ENV PORT={{.Port}}

CMD ["./{{.Name}}-service"]